# Generated by Django 3.0.1 on 2020-02-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
